apiVersion: v1
kind: Secret
metadata:
  name: mongodbservicioestudiantes
  labels:
    app.kubernetes.io/component: mongodbservicioestudiantes
    {{- include "estudiantes.labels" . | nindent 4 }}
type: Opaque
data:
  mongo_url: {{ .Values.mongoUrl | b64enc }}